name = "fpjs-metrics-beta"
type = "javascript"
account_id = ""
zone_id = ""
route = ""

[build.upload]
format = "modules"
dir = './src'
main = "./index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]
