name: Update worker's repository from the public template

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Sync changes
        uses: sshelomentsev/update-repository@v1.2.0
        with:
          source: https://github.com/necipallef2/cf_worker.git

